// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gsPEN_cpp
Rcpp::List gsPEN_cpp(arma::Mat<double> summary_betas, arma::Col<int> ld_J, arma::Mat<int> index_matrix, arma::Col<int> index_J, arma::Col<double> ld_vec, arma::Mat<double> SD_vec, arma::Mat<double> tuning_matrix, arma::Col<int> dims, arma::Col<double> params);
RcppExport SEXP _PANPRSnext_gsPEN_cpp(SEXP summary_betasSEXP, SEXP ld_JSEXP, SEXP index_matrixSEXP, SEXP index_JSEXP, SEXP ld_vecSEXP, SEXP SD_vecSEXP, SEXP tuning_matrixSEXP, SEXP dimsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type summary_betas(summary_betasSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type ld_J(ld_JSEXP);
    Rcpp::traits::input_parameter< arma::Mat<int> >::type index_matrix(index_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type index_J(index_JSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type ld_vec(ld_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type SD_vec(SD_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type tuning_matrix(tuning_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(gsPEN_cpp(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, dims, params));
    return rcpp_result_gen;
END_RCPP
}
// gsPEN_sparse_cpp
Rcpp::List gsPEN_sparse_cpp(arma::Mat<double> summary_betas, arma::Col<int> ld_J, arma::Mat<int> index_matrix, arma::Col<int> index_J, arma::Col<double> ld_vec, arma::Mat<double> SD_vec, arma::Mat<double> tuning_matrix, arma::Col<int> dims, arma::Col<double> params);
RcppExport SEXP _PANPRSnext_gsPEN_sparse_cpp(SEXP summary_betasSEXP, SEXP ld_JSEXP, SEXP index_matrixSEXP, SEXP index_JSEXP, SEXP ld_vecSEXP, SEXP SD_vecSEXP, SEXP tuning_matrixSEXP, SEXP dimsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type summary_betas(summary_betasSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type ld_J(ld_JSEXP);
    Rcpp::traits::input_parameter< arma::Mat<int> >::type index_matrix(index_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type index_J(index_JSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type ld_vec(ld_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type SD_vec(SD_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type tuning_matrix(tuning_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(gsPEN_sparse_cpp(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, dims, params));
    return rcpp_result_gen;
END_RCPP
}
// gsfPEN_cpp
Rcpp::List gsfPEN_cpp(arma::Mat<double> summary_betas, arma::Col<int> ld_J, arma::Mat<int> index_matrix, arma::Col<int> index_J, arma::Col<double> ld_vec, arma::Mat<double> SD_vec, arma::Mat<double> tuning_matrix, arma::Col<double> lambda0_vec, arma::Mat<double> z_matrix, arma::Col<double> lambda_vec_func, arma::Mat<int> func_lambda, arma::Col<int> Ifunc_SNP, arma::Col<int> dims, arma::Col<double> params);
RcppExport SEXP _PANPRSnext_gsfPEN_cpp(SEXP summary_betasSEXP, SEXP ld_JSEXP, SEXP index_matrixSEXP, SEXP index_JSEXP, SEXP ld_vecSEXP, SEXP SD_vecSEXP, SEXP tuning_matrixSEXP, SEXP lambda0_vecSEXP, SEXP z_matrixSEXP, SEXP lambda_vec_funcSEXP, SEXP func_lambdaSEXP, SEXP Ifunc_SNPSEXP, SEXP dimsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type summary_betas(summary_betasSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type ld_J(ld_JSEXP);
    Rcpp::traits::input_parameter< arma::Mat<int> >::type index_matrix(index_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type index_J(index_JSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type ld_vec(ld_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type SD_vec(SD_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type tuning_matrix(tuning_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type lambda0_vec(lambda0_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type z_matrix(z_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type lambda_vec_func(lambda_vec_funcSEXP);
    Rcpp::traits::input_parameter< arma::Mat<int> >::type func_lambda(func_lambdaSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type Ifunc_SNP(Ifunc_SNPSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(gsfPEN_cpp(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, lambda0_vec, z_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params));
    return rcpp_result_gen;
END_RCPP
}
// gsfPEN_sparse_cpp
Rcpp::List gsfPEN_sparse_cpp(arma::Mat<double> summary_betas, arma::Col<int> ld_J, arma::Mat<int> index_matrix, arma::Col<int> index_J, arma::Col<double> ld_vec, arma::Mat<double> SD_vec, arma::Mat<double> tuning_matrix, arma::Col<double> lambda0_vec, arma::Mat<double> z_matrix, arma::Col<double> lambda_vec_func, arma::Mat<int> func_lambda, arma::Col<int> Ifunc_SNP, arma::Col<int> dims, arma::Col<double> params);
RcppExport SEXP _PANPRSnext_gsfPEN_sparse_cpp(SEXP summary_betasSEXP, SEXP ld_JSEXP, SEXP index_matrixSEXP, SEXP index_JSEXP, SEXP ld_vecSEXP, SEXP SD_vecSEXP, SEXP tuning_matrixSEXP, SEXP lambda0_vecSEXP, SEXP z_matrixSEXP, SEXP lambda_vec_funcSEXP, SEXP func_lambdaSEXP, SEXP Ifunc_SNPSEXP, SEXP dimsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<double> >::type summary_betas(summary_betasSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type ld_J(ld_JSEXP);
    Rcpp::traits::input_parameter< arma::Mat<int> >::type index_matrix(index_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type index_J(index_JSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type ld_vec(ld_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type SD_vec(SD_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type tuning_matrix(tuning_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type lambda0_vec(lambda0_vecSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double> >::type z_matrix(z_matrixSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type lambda_vec_func(lambda_vec_funcSEXP);
    Rcpp::traits::input_parameter< arma::Mat<int> >::type func_lambda(func_lambdaSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type Ifunc_SNP(Ifunc_SNPSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< arma::Col<double> >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(gsfPEN_sparse_cpp(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, lambda0_vec, z_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PANPRSnext_gsPEN_cpp", (DL_FUNC) &_PANPRSnext_gsPEN_cpp, 9},
    {"_PANPRSnext_gsPEN_sparse_cpp", (DL_FUNC) &_PANPRSnext_gsPEN_sparse_cpp, 9},
    {"_PANPRSnext_gsfPEN_cpp", (DL_FUNC) &_PANPRSnext_gsfPEN_cpp, 14},
    {"_PANPRSnext_gsfPEN_sparse_cpp", (DL_FUNC) &_PANPRSnext_gsfPEN_sparse_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_PANPRSnext(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
