# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main CPP function
#' @param summary_betas matrix of summary statistics
#' @param ld_J vector of indices of SNPs in LD with the current SNP
#' @param index_matrix matrix of indices of SNPs in LD with the current SNP
#' @param index_J vector of indices of SNPs in LD with the current SNP
#' @param ld_vec vector of LD values
#' @param SD_vec matrix of SD values
#' @param tuning_matrix matrix of tuning parameters
#' @param dims vector of dimensions
#' @param params vector of parameters
gsPEN_cpp <- function(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, dims, params) {
    .Call(`_PANPRSnext_gsPEN_cpp`, summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, dims, params)
}

#' Main CPP function
#' @param summary_betas matrix of summary statistics
#' @param ld_J vector of indices of SNPs in LD with the current SNP
#' @param index_matrix matrix of indices of SNPs in LD with the current SNP
#' @param index_J vector of indices of SNPs in LD with the current SNP
#' @param ld_vec vector of LD values
#' @param SD_vec matrix of SD values
#' @param tuning_matrix matrix of tuning parameters
#' @param dims vector of dimensions
#' @param params vector of parameters
gsPEN_sparse_cpp <- function(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, dims, params) {
    .Call(`_PANPRSnext_gsPEN_sparse_cpp`, summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, dims, params)
}

#' Main CPP function
#' @param summary_betas matrix of summary statistics
#' @param ld_J vector of indices of SNPs in LD with the current SNP
#' @param index_matrix matrix of indices of SNPs in LD with the current SNP
#' @param index_J vector of indices of SNPs in LD with the current SNP
#' @param ld_vec vector of LD values
#' @param SD_vec matrix of SD values
#' @param tuning_matrix matrix of tuning parameters
#' @param lambda0_vec vector of lambda0 values
#' @param z_matrix matrix of z values
#' @param lambda_vec_func vector of lambda values
#' @param func_lambda matrix of lambda values
#' @param Ifunc_SNP vector of indices of SNPs in LD with the current SNP
#' @param dims vector of dimensions
#' @param params vector of parameters
gsfPEN_cpp <- function(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, lambda0_vec, z_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params) {
    .Call(`_PANPRSnext_gsfPEN_cpp`, summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, lambda0_vec, z_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params)
}

#' Main CPP function
#' @param summary_betas matrix of summary statistics
#' @param ld_J vector of indices of SNPs in LD with the current SNP
#' @param index_matrix matrix of indices of SNPs in LD with the current SNP
#' @param index_J vector of indices of SNPs in LD with the current SNP
#' @param ld_vec vector of LD values
#' @param SD_vec matrix of SD values
#' @param tuning_matrix matrix of tuning parameters
#' @param lambda0_vec vector of lambda0 values
#' @param z_matrix matrix of z values
#' @param lambda_vec_func vector of lambda values
#' @param func_lambda matrix of lambda values
#' @param Ifunc_SNP vector of indices of SNPs in LD with the current SNP
#' @param dims vector of dimensions
#' @param params vector of parameters
gsfPEN_sparse_cpp <- function(summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, lambda0_vec, z_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params) {
    .Call(`_PANPRSnext_gsfPEN_sparse_cpp`, summary_betas, ld_J, index_matrix, index_J, ld_vec, SD_vec, tuning_matrix, lambda0_vec, z_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params)
}

